
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'AboutCover': typeof import("../components/AboutCover.vue")['default']
    'ApplicationLogo': typeof import("../components/ApplicationLogo.vue")['default']
    'AuthCard': typeof import("../components/AuthCard.vue")['default']
    'AuthSessionStatus': typeof import("../components/AuthSessionStatus.vue")['default']
    'BackGroundImage': typeof import("../components/BackGroundImage.vue")['default']
    'Button': typeof import("../components/Button.vue")['default']
    'Card': typeof import("../components/Card.vue")['default']
    'Carousel': typeof import("../components/Carousel.vue")['default']
    'CarouselBanner': typeof import("../components/CarouselBanner.vue")['default']
    'CourseDialog': typeof import("../components/Course/CourseDialog.vue")['default']
    'CourseDataTable': typeof import("../components/Course/DataTable.vue")['default']
    'CourseDataTableDropDown': typeof import("../components/Course/DataTableDropDown.vue")['default']
    'CourseDeleteBookDrawer': typeof import("../components/Course/DeleteBookDrawer.vue")['default']
    'CourseNew': typeof import("../components/Course/New.vue")['default']
    'CourseCard': typeof import("../components/CourseCard.vue")['default']
    'CourseSection': typeof import("../components/CourseSection.vue")['default']
    'CoursesCover': typeof import("../components/CoursesCover.vue")['default']
    'DropdownButton': typeof import("../components/Dropdown/Button.vue")['default']
    'Dropdown': typeof import("../components/Dropdown/Dropdown.vue")['default']
    'DropdownLink': typeof import("../components/Dropdown/Link.vue")['default']
    'FlashMessages': typeof import("../components/FlashMessages.vue")['default']
    'Input': typeof import("../components/Input.vue")['default']
    'Label': typeof import("../components/Label.vue")['default']
    'Logo': typeof import("../components/Logo.vue")['default']
    'NavigationLink': typeof import("../components/Navigation/Link.vue")['default']
    'Navigation': typeof import("../components/Navigation/Navigation.vue")['default']
    'NavigationResponsiveButton': typeof import("../components/Navigation/ResponsiveButton.vue")['default']
    'NavigationResponsiveLink': typeof import("../components/Navigation/ResponsiveLink.vue")['default']
    'OurCommunityCover': typeof import("../components/OurCommunityCover.vue")['default']
    'PaymentDialog': typeof import("../components/PaymentDialog.vue")['default']
    'SidebarMenu': typeof import("../components/Sidebar/Menu.vue")['default']
    'Sidebar': typeof import("../components/Sidebar/index.vue")['default']
    'LayoutFullLogo': typeof import("../components/layout/full/logo/Logo.vue")['default']
    'LayoutFullLogoDark': typeof import("../components/layout/full/logo/LogoDark.vue")['default']
    'LayoutFullVerticalHeaderNotificationDD': typeof import("../components/layout/full/vertical-header/NotificationDD.vue")['default']
    'LayoutFullVerticalHeaderProfileDD': typeof import("../components/layout/full/vertical-header/ProfileDD.vue")['default']
    'LayoutFullVerticalSidebarExtraBox': typeof import("../components/layout/full/vertical-sidebar/ExtraBox/index.vue")['default']
    'LayoutFullVerticalSidebarNavGroup': typeof import("../components/layout/full/vertical-sidebar/NavGroup/index.vue")['default']
    'LayoutFullVerticalSidebarNavItem': typeof import("../components/layout/full/vertical-sidebar/NavItem/index.vue")['default']
    'LayoutFullVerticalSidebarItem': typeof import("../components/layout/full/vertical-sidebar/sidebarItem")['default']
    'PaymentsDataTable': typeof import("../components/payments/DataTable.vue")['default']
    'PaymentsDataTableDropDown': typeof import("../components/payments/DataTableDropDown.vue")['default']
    'StudentsDataTable': typeof import("../components/students/DataTable.vue")['default']
    'UAccordion': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Accordion.vue")['default']
    'UAlert': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Alert.vue")['default']
    'UAvatar': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Avatar.vue")['default']
    'UAvatarGroup': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/AvatarGroup")['default']
    'UBadge': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Badge.vue")['default']
    'UButton': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Button.vue")['default']
    'UButtonGroup': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/ButtonGroup")['default']
    'UCarousel': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Carousel.vue")['default']
    'UChip': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Chip.vue")['default']
    'UDropdown': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Dropdown.vue")['default']
    'UIcon': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Icon.vue")['default']
    'UKbd': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Kbd.vue")['default']
    'ULink': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Link.vue")['default']
    'UMeter': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Meter.vue")['default']
    'UMeterGroup': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/MeterGroup")['default']
    'UProgress': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Progress.vue")['default']
    'UCheckbox': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Checkbox.vue")['default']
    'UForm': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Form.vue")['default']
    'UFormGroup': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/FormGroup.vue")['default']
    'UInput': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Input.vue")['default']
    'UInputMenu': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/InputMenu.vue")['default']
    'URadio': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Radio.vue")['default']
    'URadioGroup': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/RadioGroup.vue")['default']
    'URange': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Range.vue")['default']
    'USelect': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Select.vue")['default']
    'USelectMenu': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/SelectMenu.vue")['default']
    'UTextarea': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Textarea.vue")['default']
    'UToggle': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Toggle.vue")['default']
    'UTable': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/data/Table.vue")['default']
    'UCard': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Card.vue")['default']
    'UContainer': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Container.vue")['default']
    'UDivider': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Divider.vue")['default']
    'USkeleton': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Skeleton.vue")['default']
    'UBreadcrumb': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/Breadcrumb.vue")['default']
    'UCommandPalette': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/CommandPalette.vue")['default']
    'UCommandPaletteGroup': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/CommandPaletteGroup.vue")['default']
    'UHorizontalNavigation': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/HorizontalNavigation.vue")['default']
    'UPagination': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/Pagination.vue")['default']
    'UTabs': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/Tabs.vue")['default']
    'UVerticalNavigation': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/VerticalNavigation.vue")['default']
    'UContextMenu': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/ContextMenu.vue")['default']
    'UModal': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Modal.vue")['default']
    'UModals': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Modals.client.vue")['default']
    'UNotification': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Notification.vue")['default']
    'UNotifications': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Notifications.vue")['default']
    'UPopover': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Popover.vue")['default']
    'USlideover': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Slideover.vue")['default']
    'USlideovers': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Slideovers.client.vue")['default']
    'UTooltip': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Tooltip.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'Icon': typeof import("../node_modules/@nuxt/icon/dist/runtime/components/index")['default']
    'ColorScheme': typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
    'Slide': typeof import("../node_modules/vue3-carousel/dist/carousel.es")['Slide']
    'Pagination': typeof import("../node_modules/vue3-carousel/dist/carousel.es")['Pagination']
    'Accordion': typeof import("../components/ui/accordion/index")['Accordion']
    'AccordionContent': typeof import("../components/ui/accordion/index")['AccordionContent']
    'AccordionItem': typeof import("../components/ui/accordion/index")['AccordionItem']
    'AccordionTrigger': typeof import("../components/ui/accordion/index")['AccordionTrigger']
    'AlertDialog': typeof import("../components/ui/alert-dialog/index")['AlertDialog']
    'AlertDialogTrigger': typeof import("../components/ui/alert-dialog/index")['AlertDialogTrigger']
    'AlertDialogContent': typeof import("../components/ui/alert-dialog/index")['AlertDialogContent']
    'AlertDialogHeader': typeof import("../components/ui/alert-dialog/index")['AlertDialogHeader']
    'AlertDialogTitle': typeof import("../components/ui/alert-dialog/index")['AlertDialogTitle']
    'AlertDialogDescription': typeof import("../components/ui/alert-dialog/index")['AlertDialogDescription']
    'AlertDialogFooter': typeof import("../components/ui/alert-dialog/index")['AlertDialogFooter']
    'AlertDialogAction': typeof import("../components/ui/alert-dialog/index")['AlertDialogAction']
    'AlertDialogCancel': typeof import("../components/ui/alert-dialog/index")['AlertDialogCancel']
    'Badge': typeof import("../components/ui/badge/index")['Badge']
    'Calendar': typeof import("../components/ui/calendar/index")['Calendar']
    'CalendarCell': typeof import("../components/ui/calendar/index")['CalendarCell']
    'CalendarCellTrigger': typeof import("../components/ui/calendar/index")['CalendarCellTrigger']
    'CalendarGrid': typeof import("../components/ui/calendar/index")['CalendarGrid']
    'CalendarGridBody': typeof import("../components/ui/calendar/index")['CalendarGridBody']
    'CalendarGridHead': typeof import("../components/ui/calendar/index")['CalendarGridHead']
    'CalendarGridRow': typeof import("../components/ui/calendar/index")['CalendarGridRow']
    'CalendarHeadCell': typeof import("../components/ui/calendar/index")['CalendarHeadCell']
    'CalendarHeader': typeof import("../components/ui/calendar/index")['CalendarHeader']
    'CalendarHeading': typeof import("../components/ui/calendar/index")['CalendarHeading']
    'CalendarNextButton': typeof import("../components/ui/calendar/index")['CalendarNextButton']
    'CalendarPrevButton': typeof import("../components/ui/calendar/index")['CalendarPrevButton']
    'CardHeader': typeof import("../components/ui/card/index")['CardHeader']
    'CardTitle': typeof import("../components/ui/card/index")['CardTitle']
    'CardDescription': typeof import("../components/ui/card/index")['CardDescription']
    'CardContent': typeof import("../components/ui/card/index")['CardContent']
    'CardFooter': typeof import("../components/ui/card/index")['CardFooter']
    'CarouselContent': typeof import("../components/ui/carousel/index")['CarouselContent']
    'CarouselItem': typeof import("../components/ui/carousel/index")['CarouselItem']
    'CarouselPrevious': typeof import("../components/ui/carousel/index")['CarouselPrevious']
    'CarouselNext': typeof import("../components/ui/carousel/index")['CarouselNext']
    'CarouselApi': typeof import("../components/ui/carousel/index")['CarouselApi']
    'Checkbox': typeof import("../components/ui/checkbox/index")['Checkbox']
    'Dialog': typeof import("../components/ui/dialog/index")['Dialog']
    'DialogClose': typeof import("../components/ui/dialog/index")['DialogClose']
    'DialogTrigger': typeof import("../components/ui/dialog/index")['DialogTrigger']
    'DialogHeader': typeof import("../components/ui/dialog/index")['DialogHeader']
    'DialogTitle': typeof import("../components/ui/dialog/index")['DialogTitle']
    'DialogDescription': typeof import("../components/ui/dialog/index")['DialogDescription']
    'DialogContent': typeof import("../components/ui/dialog/index")['DialogContent']
    'DialogScrollContent': typeof import("../components/ui/dialog/index")['DialogScrollContent']
    'DialogFooter': typeof import("../components/ui/dialog/index")['DialogFooter']
    'DropdownMenuPortal': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuPortal']
    'DropdownMenu': typeof import("../components/ui/dropdown-menu/index")['DropdownMenu']
    'DropdownMenuTrigger': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuTrigger']
    'DropdownMenuContent': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuContent']
    'DropdownMenuGroup': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuGroup']
    'DropdownMenuRadioGroup': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioGroup']
    'DropdownMenuItem': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuItem']
    'DropdownMenuCheckboxItem': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuCheckboxItem']
    'DropdownMenuRadioItem': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioItem']
    'DropdownMenuShortcut': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuShortcut']
    'DropdownMenuSeparator': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSeparator']
    'DropdownMenuLabel': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuLabel']
    'DropdownMenuSub': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSub']
    'DropdownMenuSubTrigger': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubTrigger']
    'DropdownMenuSubContent': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubContent']
    'Form': typeof import("../components/ui/form/index")['Form']
    'FormField': typeof import("../components/ui/form/index")['FormField']
    'FormItem': typeof import("../components/ui/form/index")['FormItem']
    'FormLabel': typeof import("../components/ui/form/index")['FormLabel']
    'FormControl': typeof import("../components/ui/form/index")['FormControl']
    'FormMessage': typeof import("../components/ui/form/index")['FormMessage']
    'FormDescription': typeof import("../components/ui/form/index")['FormDescription']
    'FORMITEMINJECTIONKEY': typeof import("../components/ui/form/index")['FORM_ITEM_INJECTION_KEY']
    'Popover': typeof import("../components/ui/popover/index")['Popover']
    'PopoverTrigger': typeof import("../components/ui/popover/index")['PopoverTrigger']
    'PopoverContent': typeof import("../components/ui/popover/index")['PopoverContent']
    'RangeCalendar': typeof import("../components/ui/range-calendar/index")['RangeCalendar']
    'RangeCalendarCell': typeof import("../components/ui/range-calendar/index")['RangeCalendarCell']
    'RangeCalendarCellTrigger': typeof import("../components/ui/range-calendar/index")['RangeCalendarCellTrigger']
    'RangeCalendarGrid': typeof import("../components/ui/range-calendar/index")['RangeCalendarGrid']
    'RangeCalendarGridBody': typeof import("../components/ui/range-calendar/index")['RangeCalendarGridBody']
    'RangeCalendarGridHead': typeof import("../components/ui/range-calendar/index")['RangeCalendarGridHead']
    'RangeCalendarGridRow': typeof import("../components/ui/range-calendar/index")['RangeCalendarGridRow']
    'RangeCalendarHeadCell': typeof import("../components/ui/range-calendar/index")['RangeCalendarHeadCell']
    'RangeCalendarHeader': typeof import("../components/ui/range-calendar/index")['RangeCalendarHeader']
    'RangeCalendarHeading': typeof import("../components/ui/range-calendar/index")['RangeCalendarHeading']
    'RangeCalendarNextButton': typeof import("../components/ui/range-calendar/index")['RangeCalendarNextButton']
    'RangeCalendarPrevButton': typeof import("../components/ui/range-calendar/index")['RangeCalendarPrevButton']
    'Separator': typeof import("../components/ui/separator/index")['Separator']
    'Sheet': typeof import("../components/ui/sheet/index")['Sheet']
    'SheetTrigger': typeof import("../components/ui/sheet/index")['SheetTrigger']
    'SheetClose': typeof import("../components/ui/sheet/index")['SheetClose']
    'SheetContent': typeof import("../components/ui/sheet/index")['SheetContent']
    'SheetHeader': typeof import("../components/ui/sheet/index")['SheetHeader']
    'SheetTitle': typeof import("../components/ui/sheet/index")['SheetTitle']
    'SheetDescription': typeof import("../components/ui/sheet/index")['SheetDescription']
    'SheetFooter': typeof import("../components/ui/sheet/index")['SheetFooter']
    'Table': typeof import("../components/ui/table/index")['Table']
    'TableBody': typeof import("../components/ui/table/index")['TableBody']
    'TableCell': typeof import("../components/ui/table/index")['TableCell']
    'TableHead': typeof import("../components/ui/table/index")['TableHead']
    'TableHeader': typeof import("../components/ui/table/index")['TableHeader']
    'TableFooter': typeof import("../components/ui/table/index")['TableFooter']
    'TableRow': typeof import("../components/ui/table/index")['TableRow']
    'TableCaption': typeof import("../components/ui/table/index")['TableCaption']
    'TableEmpty': typeof import("../components/ui/table/index")['TableEmpty']
    'TagsInput': typeof import("../components/ui/tags-input/index")['TagsInput']
    'TagsInputInput': typeof import("../components/ui/tags-input/index")['TagsInputInput']
    'TagsInputItem': typeof import("../components/ui/tags-input/index")['TagsInputItem']
    'TagsInputItemDelete': typeof import("../components/ui/tags-input/index")['TagsInputItemDelete']
    'TagsInputItemText': typeof import("../components/ui/tags-input/index")['TagsInputItemText']
    'Textarea': typeof import("../components/ui/textarea/index")['Textarea']
    'Toaster': typeof import("../components/ui/toast/index")['Toaster']
    'Toast': typeof import("../components/ui/toast/index")['Toast']
    'ToastViewport': typeof import("../components/ui/toast/index")['ToastViewport']
    'ToastAction': typeof import("../components/ui/toast/index")['ToastAction']
    'ToastClose': typeof import("../components/ui/toast/index")['ToastClose']
    'ToastTitle': typeof import("../components/ui/toast/index")['ToastTitle']
    'ToastDescription': typeof import("../components/ui/toast/index")['ToastDescription']
    'ToastProvider': typeof import("../components/ui/toast/index")['ToastProvider']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'UModals': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
    'USlideovers': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyAboutCover': typeof import("../components/AboutCover.vue")['default']
    'LazyApplicationLogo': typeof import("../components/ApplicationLogo.vue")['default']
    'LazyAuthCard': typeof import("../components/AuthCard.vue")['default']
    'LazyAuthSessionStatus': typeof import("../components/AuthSessionStatus.vue")['default']
    'LazyBackGroundImage': typeof import("../components/BackGroundImage.vue")['default']
    'LazyButton': typeof import("../components/Button.vue")['default']
    'LazyCard': typeof import("../components/Card.vue")['default']
    'LazyCarousel': typeof import("../components/Carousel.vue")['default']
    'LazyCarouselBanner': typeof import("../components/CarouselBanner.vue")['default']
    'LazyCourseDialog': typeof import("../components/Course/CourseDialog.vue")['default']
    'LazyCourseDataTable': typeof import("../components/Course/DataTable.vue")['default']
    'LazyCourseDataTableDropDown': typeof import("../components/Course/DataTableDropDown.vue")['default']
    'LazyCourseDeleteBookDrawer': typeof import("../components/Course/DeleteBookDrawer.vue")['default']
    'LazyCourseNew': typeof import("../components/Course/New.vue")['default']
    'LazyCourseCard': typeof import("../components/CourseCard.vue")['default']
    'LazyCourseSection': typeof import("../components/CourseSection.vue")['default']
    'LazyCoursesCover': typeof import("../components/CoursesCover.vue")['default']
    'LazyDropdownButton': typeof import("../components/Dropdown/Button.vue")['default']
    'LazyDropdown': typeof import("../components/Dropdown/Dropdown.vue")['default']
    'LazyDropdownLink': typeof import("../components/Dropdown/Link.vue")['default']
    'LazyFlashMessages': typeof import("../components/FlashMessages.vue")['default']
    'LazyInput': typeof import("../components/Input.vue")['default']
    'LazyLabel': typeof import("../components/Label.vue")['default']
    'LazyLogo': typeof import("../components/Logo.vue")['default']
    'LazyNavigationLink': typeof import("../components/Navigation/Link.vue")['default']
    'LazyNavigation': typeof import("../components/Navigation/Navigation.vue")['default']
    'LazyNavigationResponsiveButton': typeof import("../components/Navigation/ResponsiveButton.vue")['default']
    'LazyNavigationResponsiveLink': typeof import("../components/Navigation/ResponsiveLink.vue")['default']
    'LazyOurCommunityCover': typeof import("../components/OurCommunityCover.vue")['default']
    'LazyPaymentDialog': typeof import("../components/PaymentDialog.vue")['default']
    'LazySidebarMenu': typeof import("../components/Sidebar/Menu.vue")['default']
    'LazySidebar': typeof import("../components/Sidebar/index.vue")['default']
    'LazyLayoutFullLogo': typeof import("../components/layout/full/logo/Logo.vue")['default']
    'LazyLayoutFullLogoDark': typeof import("../components/layout/full/logo/LogoDark.vue")['default']
    'LazyLayoutFullVerticalHeaderNotificationDD': typeof import("../components/layout/full/vertical-header/NotificationDD.vue")['default']
    'LazyLayoutFullVerticalHeaderProfileDD': typeof import("../components/layout/full/vertical-header/ProfileDD.vue")['default']
    'LazyLayoutFullVerticalSidebarExtraBox': typeof import("../components/layout/full/vertical-sidebar/ExtraBox/index.vue")['default']
    'LazyLayoutFullVerticalSidebarNavGroup': typeof import("../components/layout/full/vertical-sidebar/NavGroup/index.vue")['default']
    'LazyLayoutFullVerticalSidebarNavItem': typeof import("../components/layout/full/vertical-sidebar/NavItem/index.vue")['default']
    'LazyLayoutFullVerticalSidebarItem': typeof import("../components/layout/full/vertical-sidebar/sidebarItem")['default']
    'LazyPaymentsDataTable': typeof import("../components/payments/DataTable.vue")['default']
    'LazyPaymentsDataTableDropDown': typeof import("../components/payments/DataTableDropDown.vue")['default']
    'LazyStudentsDataTable': typeof import("../components/students/DataTable.vue")['default']
    'LazyUAccordion': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Accordion.vue")['default']
    'LazyUAlert': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Alert.vue")['default']
    'LazyUAvatar': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Avatar.vue")['default']
    'LazyUAvatarGroup': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/AvatarGroup")['default']
    'LazyUBadge': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Badge.vue")['default']
    'LazyUButton': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Button.vue")['default']
    'LazyUButtonGroup': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/ButtonGroup")['default']
    'LazyUCarousel': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Carousel.vue")['default']
    'LazyUChip': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Chip.vue")['default']
    'LazyUDropdown': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Dropdown.vue")['default']
    'LazyUIcon': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Icon.vue")['default']
    'LazyUKbd': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Kbd.vue")['default']
    'LazyULink': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Link.vue")['default']
    'LazyUMeter': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Meter.vue")['default']
    'LazyUMeterGroup': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/MeterGroup")['default']
    'LazyUProgress': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Progress.vue")['default']
    'LazyUCheckbox': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Checkbox.vue")['default']
    'LazyUForm': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Form.vue")['default']
    'LazyUFormGroup': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/FormGroup.vue")['default']
    'LazyUInput': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Input.vue")['default']
    'LazyUInputMenu': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/InputMenu.vue")['default']
    'LazyURadio': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Radio.vue")['default']
    'LazyURadioGroup': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/RadioGroup.vue")['default']
    'LazyURange': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Range.vue")['default']
    'LazyUSelect': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Select.vue")['default']
    'LazyUSelectMenu': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/SelectMenu.vue")['default']
    'LazyUTextarea': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Textarea.vue")['default']
    'LazyUToggle': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Toggle.vue")['default']
    'LazyUTable': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/data/Table.vue")['default']
    'LazyUCard': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Card.vue")['default']
    'LazyUContainer': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Container.vue")['default']
    'LazyUDivider': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Divider.vue")['default']
    'LazyUSkeleton': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Skeleton.vue")['default']
    'LazyUBreadcrumb': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/Breadcrumb.vue")['default']
    'LazyUCommandPalette': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/CommandPalette.vue")['default']
    'LazyUCommandPaletteGroup': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/CommandPaletteGroup.vue")['default']
    'LazyUHorizontalNavigation': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/HorizontalNavigation.vue")['default']
    'LazyUPagination': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/Pagination.vue")['default']
    'LazyUTabs': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/Tabs.vue")['default']
    'LazyUVerticalNavigation': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/VerticalNavigation.vue")['default']
    'LazyUContextMenu': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/ContextMenu.vue")['default']
    'LazyUModal': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Modal.vue")['default']
    'LazyUModals': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Modals.client.vue")['default']
    'LazyUNotification': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Notification.vue")['default']
    'LazyUNotifications': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Notifications.vue")['default']
    'LazyUPopover': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Popover.vue")['default']
    'LazyUSlideover': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Slideover.vue")['default']
    'LazyUSlideovers': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Slideovers.client.vue")['default']
    'LazyUTooltip': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Tooltip.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyIcon': typeof import("../node_modules/@nuxt/icon/dist/runtime/components/index")['default']
    'LazyColorScheme': typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
    'LazySlide': typeof import("../node_modules/vue3-carousel/dist/carousel.es")['Slide']
    'LazyPagination': typeof import("../node_modules/vue3-carousel/dist/carousel.es")['Pagination']
    'LazyAccordion': typeof import("../components/ui/accordion/index")['Accordion']
    'LazyAccordionContent': typeof import("../components/ui/accordion/index")['AccordionContent']
    'LazyAccordionItem': typeof import("../components/ui/accordion/index")['AccordionItem']
    'LazyAccordionTrigger': typeof import("../components/ui/accordion/index")['AccordionTrigger']
    'LazyAlertDialog': typeof import("../components/ui/alert-dialog/index")['AlertDialog']
    'LazyAlertDialogTrigger': typeof import("../components/ui/alert-dialog/index")['AlertDialogTrigger']
    'LazyAlertDialogContent': typeof import("../components/ui/alert-dialog/index")['AlertDialogContent']
    'LazyAlertDialogHeader': typeof import("../components/ui/alert-dialog/index")['AlertDialogHeader']
    'LazyAlertDialogTitle': typeof import("../components/ui/alert-dialog/index")['AlertDialogTitle']
    'LazyAlertDialogDescription': typeof import("../components/ui/alert-dialog/index")['AlertDialogDescription']
    'LazyAlertDialogFooter': typeof import("../components/ui/alert-dialog/index")['AlertDialogFooter']
    'LazyAlertDialogAction': typeof import("../components/ui/alert-dialog/index")['AlertDialogAction']
    'LazyAlertDialogCancel': typeof import("../components/ui/alert-dialog/index")['AlertDialogCancel']
    'LazyBadge': typeof import("../components/ui/badge/index")['Badge']
    'LazyCalendar': typeof import("../components/ui/calendar/index")['Calendar']
    'LazyCalendarCell': typeof import("../components/ui/calendar/index")['CalendarCell']
    'LazyCalendarCellTrigger': typeof import("../components/ui/calendar/index")['CalendarCellTrigger']
    'LazyCalendarGrid': typeof import("../components/ui/calendar/index")['CalendarGrid']
    'LazyCalendarGridBody': typeof import("../components/ui/calendar/index")['CalendarGridBody']
    'LazyCalendarGridHead': typeof import("../components/ui/calendar/index")['CalendarGridHead']
    'LazyCalendarGridRow': typeof import("../components/ui/calendar/index")['CalendarGridRow']
    'LazyCalendarHeadCell': typeof import("../components/ui/calendar/index")['CalendarHeadCell']
    'LazyCalendarHeader': typeof import("../components/ui/calendar/index")['CalendarHeader']
    'LazyCalendarHeading': typeof import("../components/ui/calendar/index")['CalendarHeading']
    'LazyCalendarNextButton': typeof import("../components/ui/calendar/index")['CalendarNextButton']
    'LazyCalendarPrevButton': typeof import("../components/ui/calendar/index")['CalendarPrevButton']
    'LazyCardHeader': typeof import("../components/ui/card/index")['CardHeader']
    'LazyCardTitle': typeof import("../components/ui/card/index")['CardTitle']
    'LazyCardDescription': typeof import("../components/ui/card/index")['CardDescription']
    'LazyCardContent': typeof import("../components/ui/card/index")['CardContent']
    'LazyCardFooter': typeof import("../components/ui/card/index")['CardFooter']
    'LazyCarouselContent': typeof import("../components/ui/carousel/index")['CarouselContent']
    'LazyCarouselItem': typeof import("../components/ui/carousel/index")['CarouselItem']
    'LazyCarouselPrevious': typeof import("../components/ui/carousel/index")['CarouselPrevious']
    'LazyCarouselNext': typeof import("../components/ui/carousel/index")['CarouselNext']
    'LazyCarouselApi': typeof import("../components/ui/carousel/index")['CarouselApi']
    'LazyCheckbox': typeof import("../components/ui/checkbox/index")['Checkbox']
    'LazyDialog': typeof import("../components/ui/dialog/index")['Dialog']
    'LazyDialogClose': typeof import("../components/ui/dialog/index")['DialogClose']
    'LazyDialogTrigger': typeof import("../components/ui/dialog/index")['DialogTrigger']
    'LazyDialogHeader': typeof import("../components/ui/dialog/index")['DialogHeader']
    'LazyDialogTitle': typeof import("../components/ui/dialog/index")['DialogTitle']
    'LazyDialogDescription': typeof import("../components/ui/dialog/index")['DialogDescription']
    'LazyDialogContent': typeof import("../components/ui/dialog/index")['DialogContent']
    'LazyDialogScrollContent': typeof import("../components/ui/dialog/index")['DialogScrollContent']
    'LazyDialogFooter': typeof import("../components/ui/dialog/index")['DialogFooter']
    'LazyDropdownMenuPortal': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuPortal']
    'LazyDropdownMenu': typeof import("../components/ui/dropdown-menu/index")['DropdownMenu']
    'LazyDropdownMenuTrigger': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuTrigger']
    'LazyDropdownMenuContent': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuContent']
    'LazyDropdownMenuGroup': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuGroup']
    'LazyDropdownMenuRadioGroup': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioGroup']
    'LazyDropdownMenuItem': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuItem']
    'LazyDropdownMenuCheckboxItem': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuCheckboxItem']
    'LazyDropdownMenuRadioItem': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioItem']
    'LazyDropdownMenuShortcut': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuShortcut']
    'LazyDropdownMenuSeparator': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSeparator']
    'LazyDropdownMenuLabel': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuLabel']
    'LazyDropdownMenuSub': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSub']
    'LazyDropdownMenuSubTrigger': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubTrigger']
    'LazyDropdownMenuSubContent': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubContent']
    'LazyForm': typeof import("../components/ui/form/index")['Form']
    'LazyFormField': typeof import("../components/ui/form/index")['FormField']
    'LazyFormItem': typeof import("../components/ui/form/index")['FormItem']
    'LazyFormLabel': typeof import("../components/ui/form/index")['FormLabel']
    'LazyFormControl': typeof import("../components/ui/form/index")['FormControl']
    'LazyFormMessage': typeof import("../components/ui/form/index")['FormMessage']
    'LazyFormDescription': typeof import("../components/ui/form/index")['FormDescription']
    'LazyFORMITEMINJECTIONKEY': typeof import("../components/ui/form/index")['FORM_ITEM_INJECTION_KEY']
    'LazyPopover': typeof import("../components/ui/popover/index")['Popover']
    'LazyPopoverTrigger': typeof import("../components/ui/popover/index")['PopoverTrigger']
    'LazyPopoverContent': typeof import("../components/ui/popover/index")['PopoverContent']
    'LazyRangeCalendar': typeof import("../components/ui/range-calendar/index")['RangeCalendar']
    'LazyRangeCalendarCell': typeof import("../components/ui/range-calendar/index")['RangeCalendarCell']
    'LazyRangeCalendarCellTrigger': typeof import("../components/ui/range-calendar/index")['RangeCalendarCellTrigger']
    'LazyRangeCalendarGrid': typeof import("../components/ui/range-calendar/index")['RangeCalendarGrid']
    'LazyRangeCalendarGridBody': typeof import("../components/ui/range-calendar/index")['RangeCalendarGridBody']
    'LazyRangeCalendarGridHead': typeof import("../components/ui/range-calendar/index")['RangeCalendarGridHead']
    'LazyRangeCalendarGridRow': typeof import("../components/ui/range-calendar/index")['RangeCalendarGridRow']
    'LazyRangeCalendarHeadCell': typeof import("../components/ui/range-calendar/index")['RangeCalendarHeadCell']
    'LazyRangeCalendarHeader': typeof import("../components/ui/range-calendar/index")['RangeCalendarHeader']
    'LazyRangeCalendarHeading': typeof import("../components/ui/range-calendar/index")['RangeCalendarHeading']
    'LazyRangeCalendarNextButton': typeof import("../components/ui/range-calendar/index")['RangeCalendarNextButton']
    'LazyRangeCalendarPrevButton': typeof import("../components/ui/range-calendar/index")['RangeCalendarPrevButton']
    'LazySeparator': typeof import("../components/ui/separator/index")['Separator']
    'LazySheet': typeof import("../components/ui/sheet/index")['Sheet']
    'LazySheetTrigger': typeof import("../components/ui/sheet/index")['SheetTrigger']
    'LazySheetClose': typeof import("../components/ui/sheet/index")['SheetClose']
    'LazySheetContent': typeof import("../components/ui/sheet/index")['SheetContent']
    'LazySheetHeader': typeof import("../components/ui/sheet/index")['SheetHeader']
    'LazySheetTitle': typeof import("../components/ui/sheet/index")['SheetTitle']
    'LazySheetDescription': typeof import("../components/ui/sheet/index")['SheetDescription']
    'LazySheetFooter': typeof import("../components/ui/sheet/index")['SheetFooter']
    'LazyTable': typeof import("../components/ui/table/index")['Table']
    'LazyTableBody': typeof import("../components/ui/table/index")['TableBody']
    'LazyTableCell': typeof import("../components/ui/table/index")['TableCell']
    'LazyTableHead': typeof import("../components/ui/table/index")['TableHead']
    'LazyTableHeader': typeof import("../components/ui/table/index")['TableHeader']
    'LazyTableFooter': typeof import("../components/ui/table/index")['TableFooter']
    'LazyTableRow': typeof import("../components/ui/table/index")['TableRow']
    'LazyTableCaption': typeof import("../components/ui/table/index")['TableCaption']
    'LazyTableEmpty': typeof import("../components/ui/table/index")['TableEmpty']
    'LazyTagsInput': typeof import("../components/ui/tags-input/index")['TagsInput']
    'LazyTagsInputInput': typeof import("../components/ui/tags-input/index")['TagsInputInput']
    'LazyTagsInputItem': typeof import("../components/ui/tags-input/index")['TagsInputItem']
    'LazyTagsInputItemDelete': typeof import("../components/ui/tags-input/index")['TagsInputItemDelete']
    'LazyTagsInputItemText': typeof import("../components/ui/tags-input/index")['TagsInputItemText']
    'LazyTextarea': typeof import("../components/ui/textarea/index")['Textarea']
    'LazyToaster': typeof import("../components/ui/toast/index")['Toaster']
    'LazyToast': typeof import("../components/ui/toast/index")['Toast']
    'LazyToastViewport': typeof import("../components/ui/toast/index")['ToastViewport']
    'LazyToastAction': typeof import("../components/ui/toast/index")['ToastAction']
    'LazyToastClose': typeof import("../components/ui/toast/index")['ToastClose']
    'LazyToastTitle': typeof import("../components/ui/toast/index")['ToastTitle']
    'LazyToastDescription': typeof import("../components/ui/toast/index")['ToastDescription']
    'LazyToastProvider': typeof import("../components/ui/toast/index")['ToastProvider']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyUModals': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
    'LazyUSlideovers': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const AboutCover: typeof import("../components/AboutCover.vue")['default']
export const ApplicationLogo: typeof import("../components/ApplicationLogo.vue")['default']
export const AuthCard: typeof import("../components/AuthCard.vue")['default']
export const AuthSessionStatus: typeof import("../components/AuthSessionStatus.vue")['default']
export const BackGroundImage: typeof import("../components/BackGroundImage.vue")['default']
export const Button: typeof import("../components/Button.vue")['default']
export const Card: typeof import("../components/Card.vue")['default']
export const Carousel: typeof import("../components/Carousel.vue")['default']
export const CarouselBanner: typeof import("../components/CarouselBanner.vue")['default']
export const CourseDialog: typeof import("../components/Course/CourseDialog.vue")['default']
export const CourseDataTable: typeof import("../components/Course/DataTable.vue")['default']
export const CourseDataTableDropDown: typeof import("../components/Course/DataTableDropDown.vue")['default']
export const CourseDeleteBookDrawer: typeof import("../components/Course/DeleteBookDrawer.vue")['default']
export const CourseNew: typeof import("../components/Course/New.vue")['default']
export const CourseCard: typeof import("../components/CourseCard.vue")['default']
export const CourseSection: typeof import("../components/CourseSection.vue")['default']
export const CoursesCover: typeof import("../components/CoursesCover.vue")['default']
export const DropdownButton: typeof import("../components/Dropdown/Button.vue")['default']
export const Dropdown: typeof import("../components/Dropdown/Dropdown.vue")['default']
export const DropdownLink: typeof import("../components/Dropdown/Link.vue")['default']
export const FlashMessages: typeof import("../components/FlashMessages.vue")['default']
export const Input: typeof import("../components/Input.vue")['default']
export const Label: typeof import("../components/Label.vue")['default']
export const Logo: typeof import("../components/Logo.vue")['default']
export const NavigationLink: typeof import("../components/Navigation/Link.vue")['default']
export const Navigation: typeof import("../components/Navigation/Navigation.vue")['default']
export const NavigationResponsiveButton: typeof import("../components/Navigation/ResponsiveButton.vue")['default']
export const NavigationResponsiveLink: typeof import("../components/Navigation/ResponsiveLink.vue")['default']
export const OurCommunityCover: typeof import("../components/OurCommunityCover.vue")['default']
export const PaymentDialog: typeof import("../components/PaymentDialog.vue")['default']
export const SidebarMenu: typeof import("../components/Sidebar/Menu.vue")['default']
export const Sidebar: typeof import("../components/Sidebar/index.vue")['default']
export const LayoutFullLogo: typeof import("../components/layout/full/logo/Logo.vue")['default']
export const LayoutFullLogoDark: typeof import("../components/layout/full/logo/LogoDark.vue")['default']
export const LayoutFullVerticalHeaderNotificationDD: typeof import("../components/layout/full/vertical-header/NotificationDD.vue")['default']
export const LayoutFullVerticalHeaderProfileDD: typeof import("../components/layout/full/vertical-header/ProfileDD.vue")['default']
export const LayoutFullVerticalSidebarExtraBox: typeof import("../components/layout/full/vertical-sidebar/ExtraBox/index.vue")['default']
export const LayoutFullVerticalSidebarNavGroup: typeof import("../components/layout/full/vertical-sidebar/NavGroup/index.vue")['default']
export const LayoutFullVerticalSidebarNavItem: typeof import("../components/layout/full/vertical-sidebar/NavItem/index.vue")['default']
export const LayoutFullVerticalSidebarItem: typeof import("../components/layout/full/vertical-sidebar/sidebarItem")['default']
export const PaymentsDataTable: typeof import("../components/payments/DataTable.vue")['default']
export const PaymentsDataTableDropDown: typeof import("../components/payments/DataTableDropDown.vue")['default']
export const StudentsDataTable: typeof import("../components/students/DataTable.vue")['default']
export const UAccordion: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Accordion.vue")['default']
export const UAlert: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Alert.vue")['default']
export const UAvatar: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Avatar.vue")['default']
export const UAvatarGroup: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/AvatarGroup")['default']
export const UBadge: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Badge.vue")['default']
export const UButton: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Button.vue")['default']
export const UButtonGroup: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/ButtonGroup")['default']
export const UCarousel: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Carousel.vue")['default']
export const UChip: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Chip.vue")['default']
export const UDropdown: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Dropdown.vue")['default']
export const UIcon: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Icon.vue")['default']
export const UKbd: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Kbd.vue")['default']
export const ULink: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Link.vue")['default']
export const UMeter: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Meter.vue")['default']
export const UMeterGroup: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/MeterGroup")['default']
export const UProgress: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Progress.vue")['default']
export const UCheckbox: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Checkbox.vue")['default']
export const UForm: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Form.vue")['default']
export const UFormGroup: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/FormGroup.vue")['default']
export const UInput: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Input.vue")['default']
export const UInputMenu: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/InputMenu.vue")['default']
export const URadio: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Radio.vue")['default']
export const URadioGroup: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/RadioGroup.vue")['default']
export const URange: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Range.vue")['default']
export const USelect: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Select.vue")['default']
export const USelectMenu: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/SelectMenu.vue")['default']
export const UTextarea: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Textarea.vue")['default']
export const UToggle: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Toggle.vue")['default']
export const UTable: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/data/Table.vue")['default']
export const UCard: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Card.vue")['default']
export const UContainer: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Container.vue")['default']
export const UDivider: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Divider.vue")['default']
export const USkeleton: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Skeleton.vue")['default']
export const UBreadcrumb: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/Breadcrumb.vue")['default']
export const UCommandPalette: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/CommandPalette.vue")['default']
export const UCommandPaletteGroup: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/CommandPaletteGroup.vue")['default']
export const UHorizontalNavigation: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/HorizontalNavigation.vue")['default']
export const UPagination: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/Pagination.vue")['default']
export const UTabs: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/Tabs.vue")['default']
export const UVerticalNavigation: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/VerticalNavigation.vue")['default']
export const UContextMenu: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/ContextMenu.vue")['default']
export const UModal: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Modal.vue")['default']
export const UModals: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Modals.client.vue")['default']
export const UNotification: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Notification.vue")['default']
export const UNotifications: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Notifications.vue")['default']
export const UPopover: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Popover.vue")['default']
export const USlideover: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Slideover.vue")['default']
export const USlideovers: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Slideovers.client.vue")['default']
export const UTooltip: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Tooltip.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const Icon: typeof import("../node_modules/@nuxt/icon/dist/runtime/components/index")['default']
export const ColorScheme: typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
export const Slide: typeof import("../node_modules/vue3-carousel/dist/carousel.es")['Slide']
export const Pagination: typeof import("../node_modules/vue3-carousel/dist/carousel.es")['Pagination']
export const Accordion: typeof import("../components/ui/accordion/index")['Accordion']
export const AccordionContent: typeof import("../components/ui/accordion/index")['AccordionContent']
export const AccordionItem: typeof import("../components/ui/accordion/index")['AccordionItem']
export const AccordionTrigger: typeof import("../components/ui/accordion/index")['AccordionTrigger']
export const AlertDialog: typeof import("../components/ui/alert-dialog/index")['AlertDialog']
export const AlertDialogTrigger: typeof import("../components/ui/alert-dialog/index")['AlertDialogTrigger']
export const AlertDialogContent: typeof import("../components/ui/alert-dialog/index")['AlertDialogContent']
export const AlertDialogHeader: typeof import("../components/ui/alert-dialog/index")['AlertDialogHeader']
export const AlertDialogTitle: typeof import("../components/ui/alert-dialog/index")['AlertDialogTitle']
export const AlertDialogDescription: typeof import("../components/ui/alert-dialog/index")['AlertDialogDescription']
export const AlertDialogFooter: typeof import("../components/ui/alert-dialog/index")['AlertDialogFooter']
export const AlertDialogAction: typeof import("../components/ui/alert-dialog/index")['AlertDialogAction']
export const AlertDialogCancel: typeof import("../components/ui/alert-dialog/index")['AlertDialogCancel']
export const Badge: typeof import("../components/ui/badge/index")['Badge']
export const Calendar: typeof import("../components/ui/calendar/index")['Calendar']
export const CalendarCell: typeof import("../components/ui/calendar/index")['CalendarCell']
export const CalendarCellTrigger: typeof import("../components/ui/calendar/index")['CalendarCellTrigger']
export const CalendarGrid: typeof import("../components/ui/calendar/index")['CalendarGrid']
export const CalendarGridBody: typeof import("../components/ui/calendar/index")['CalendarGridBody']
export const CalendarGridHead: typeof import("../components/ui/calendar/index")['CalendarGridHead']
export const CalendarGridRow: typeof import("../components/ui/calendar/index")['CalendarGridRow']
export const CalendarHeadCell: typeof import("../components/ui/calendar/index")['CalendarHeadCell']
export const CalendarHeader: typeof import("../components/ui/calendar/index")['CalendarHeader']
export const CalendarHeading: typeof import("../components/ui/calendar/index")['CalendarHeading']
export const CalendarNextButton: typeof import("../components/ui/calendar/index")['CalendarNextButton']
export const CalendarPrevButton: typeof import("../components/ui/calendar/index")['CalendarPrevButton']
export const CardHeader: typeof import("../components/ui/card/index")['CardHeader']
export const CardTitle: typeof import("../components/ui/card/index")['CardTitle']
export const CardDescription: typeof import("../components/ui/card/index")['CardDescription']
export const CardContent: typeof import("../components/ui/card/index")['CardContent']
export const CardFooter: typeof import("../components/ui/card/index")['CardFooter']
export const CarouselContent: typeof import("../components/ui/carousel/index")['CarouselContent']
export const CarouselItem: typeof import("../components/ui/carousel/index")['CarouselItem']
export const CarouselPrevious: typeof import("../components/ui/carousel/index")['CarouselPrevious']
export const CarouselNext: typeof import("../components/ui/carousel/index")['CarouselNext']
export const CarouselApi: typeof import("../components/ui/carousel/index")['CarouselApi']
export const Checkbox: typeof import("../components/ui/checkbox/index")['Checkbox']
export const Dialog: typeof import("../components/ui/dialog/index")['Dialog']
export const DialogClose: typeof import("../components/ui/dialog/index")['DialogClose']
export const DialogTrigger: typeof import("../components/ui/dialog/index")['DialogTrigger']
export const DialogHeader: typeof import("../components/ui/dialog/index")['DialogHeader']
export const DialogTitle: typeof import("../components/ui/dialog/index")['DialogTitle']
export const DialogDescription: typeof import("../components/ui/dialog/index")['DialogDescription']
export const DialogContent: typeof import("../components/ui/dialog/index")['DialogContent']
export const DialogScrollContent: typeof import("../components/ui/dialog/index")['DialogScrollContent']
export const DialogFooter: typeof import("../components/ui/dialog/index")['DialogFooter']
export const DropdownMenuPortal: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuPortal']
export const DropdownMenu: typeof import("../components/ui/dropdown-menu/index")['DropdownMenu']
export const DropdownMenuTrigger: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuTrigger']
export const DropdownMenuContent: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuContent']
export const DropdownMenuGroup: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuGroup']
export const DropdownMenuRadioGroup: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioGroup']
export const DropdownMenuItem: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuItem']
export const DropdownMenuCheckboxItem: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuCheckboxItem']
export const DropdownMenuRadioItem: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioItem']
export const DropdownMenuShortcut: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuShortcut']
export const DropdownMenuSeparator: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSeparator']
export const DropdownMenuLabel: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuLabel']
export const DropdownMenuSub: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSub']
export const DropdownMenuSubTrigger: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubTrigger']
export const DropdownMenuSubContent: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubContent']
export const Form: typeof import("../components/ui/form/index")['Form']
export const FormField: typeof import("../components/ui/form/index")['FormField']
export const FormItem: typeof import("../components/ui/form/index")['FormItem']
export const FormLabel: typeof import("../components/ui/form/index")['FormLabel']
export const FormControl: typeof import("../components/ui/form/index")['FormControl']
export const FormMessage: typeof import("../components/ui/form/index")['FormMessage']
export const FormDescription: typeof import("../components/ui/form/index")['FormDescription']
export const FORMITEMINJECTIONKEY: typeof import("../components/ui/form/index")['FORM_ITEM_INJECTION_KEY']
export const Popover: typeof import("../components/ui/popover/index")['Popover']
export const PopoverTrigger: typeof import("../components/ui/popover/index")['PopoverTrigger']
export const PopoverContent: typeof import("../components/ui/popover/index")['PopoverContent']
export const RangeCalendar: typeof import("../components/ui/range-calendar/index")['RangeCalendar']
export const RangeCalendarCell: typeof import("../components/ui/range-calendar/index")['RangeCalendarCell']
export const RangeCalendarCellTrigger: typeof import("../components/ui/range-calendar/index")['RangeCalendarCellTrigger']
export const RangeCalendarGrid: typeof import("../components/ui/range-calendar/index")['RangeCalendarGrid']
export const RangeCalendarGridBody: typeof import("../components/ui/range-calendar/index")['RangeCalendarGridBody']
export const RangeCalendarGridHead: typeof import("../components/ui/range-calendar/index")['RangeCalendarGridHead']
export const RangeCalendarGridRow: typeof import("../components/ui/range-calendar/index")['RangeCalendarGridRow']
export const RangeCalendarHeadCell: typeof import("../components/ui/range-calendar/index")['RangeCalendarHeadCell']
export const RangeCalendarHeader: typeof import("../components/ui/range-calendar/index")['RangeCalendarHeader']
export const RangeCalendarHeading: typeof import("../components/ui/range-calendar/index")['RangeCalendarHeading']
export const RangeCalendarNextButton: typeof import("../components/ui/range-calendar/index")['RangeCalendarNextButton']
export const RangeCalendarPrevButton: typeof import("../components/ui/range-calendar/index")['RangeCalendarPrevButton']
export const Separator: typeof import("../components/ui/separator/index")['Separator']
export const Sheet: typeof import("../components/ui/sheet/index")['Sheet']
export const SheetTrigger: typeof import("../components/ui/sheet/index")['SheetTrigger']
export const SheetClose: typeof import("../components/ui/sheet/index")['SheetClose']
export const SheetContent: typeof import("../components/ui/sheet/index")['SheetContent']
export const SheetHeader: typeof import("../components/ui/sheet/index")['SheetHeader']
export const SheetTitle: typeof import("../components/ui/sheet/index")['SheetTitle']
export const SheetDescription: typeof import("../components/ui/sheet/index")['SheetDescription']
export const SheetFooter: typeof import("../components/ui/sheet/index")['SheetFooter']
export const Table: typeof import("../components/ui/table/index")['Table']
export const TableBody: typeof import("../components/ui/table/index")['TableBody']
export const TableCell: typeof import("../components/ui/table/index")['TableCell']
export const TableHead: typeof import("../components/ui/table/index")['TableHead']
export const TableHeader: typeof import("../components/ui/table/index")['TableHeader']
export const TableFooter: typeof import("../components/ui/table/index")['TableFooter']
export const TableRow: typeof import("../components/ui/table/index")['TableRow']
export const TableCaption: typeof import("../components/ui/table/index")['TableCaption']
export const TableEmpty: typeof import("../components/ui/table/index")['TableEmpty']
export const TagsInput: typeof import("../components/ui/tags-input/index")['TagsInput']
export const TagsInputInput: typeof import("../components/ui/tags-input/index")['TagsInputInput']
export const TagsInputItem: typeof import("../components/ui/tags-input/index")['TagsInputItem']
export const TagsInputItemDelete: typeof import("../components/ui/tags-input/index")['TagsInputItemDelete']
export const TagsInputItemText: typeof import("../components/ui/tags-input/index")['TagsInputItemText']
export const Textarea: typeof import("../components/ui/textarea/index")['Textarea']
export const Toaster: typeof import("../components/ui/toast/index")['Toaster']
export const Toast: typeof import("../components/ui/toast/index")['Toast']
export const ToastViewport: typeof import("../components/ui/toast/index")['ToastViewport']
export const ToastAction: typeof import("../components/ui/toast/index")['ToastAction']
export const ToastClose: typeof import("../components/ui/toast/index")['ToastClose']
export const ToastTitle: typeof import("../components/ui/toast/index")['ToastTitle']
export const ToastDescription: typeof import("../components/ui/toast/index")['ToastDescription']
export const ToastProvider: typeof import("../components/ui/toast/index")['ToastProvider']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const UModals: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const USlideovers: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyAboutCover: typeof import("../components/AboutCover.vue")['default']
export const LazyApplicationLogo: typeof import("../components/ApplicationLogo.vue")['default']
export const LazyAuthCard: typeof import("../components/AuthCard.vue")['default']
export const LazyAuthSessionStatus: typeof import("../components/AuthSessionStatus.vue")['default']
export const LazyBackGroundImage: typeof import("../components/BackGroundImage.vue")['default']
export const LazyButton: typeof import("../components/Button.vue")['default']
export const LazyCard: typeof import("../components/Card.vue")['default']
export const LazyCarousel: typeof import("../components/Carousel.vue")['default']
export const LazyCarouselBanner: typeof import("../components/CarouselBanner.vue")['default']
export const LazyCourseDialog: typeof import("../components/Course/CourseDialog.vue")['default']
export const LazyCourseDataTable: typeof import("../components/Course/DataTable.vue")['default']
export const LazyCourseDataTableDropDown: typeof import("../components/Course/DataTableDropDown.vue")['default']
export const LazyCourseDeleteBookDrawer: typeof import("../components/Course/DeleteBookDrawer.vue")['default']
export const LazyCourseNew: typeof import("../components/Course/New.vue")['default']
export const LazyCourseCard: typeof import("../components/CourseCard.vue")['default']
export const LazyCourseSection: typeof import("../components/CourseSection.vue")['default']
export const LazyCoursesCover: typeof import("../components/CoursesCover.vue")['default']
export const LazyDropdownButton: typeof import("../components/Dropdown/Button.vue")['default']
export const LazyDropdown: typeof import("../components/Dropdown/Dropdown.vue")['default']
export const LazyDropdownLink: typeof import("../components/Dropdown/Link.vue")['default']
export const LazyFlashMessages: typeof import("../components/FlashMessages.vue")['default']
export const LazyInput: typeof import("../components/Input.vue")['default']
export const LazyLabel: typeof import("../components/Label.vue")['default']
export const LazyLogo: typeof import("../components/Logo.vue")['default']
export const LazyNavigationLink: typeof import("../components/Navigation/Link.vue")['default']
export const LazyNavigation: typeof import("../components/Navigation/Navigation.vue")['default']
export const LazyNavigationResponsiveButton: typeof import("../components/Navigation/ResponsiveButton.vue")['default']
export const LazyNavigationResponsiveLink: typeof import("../components/Navigation/ResponsiveLink.vue")['default']
export const LazyOurCommunityCover: typeof import("../components/OurCommunityCover.vue")['default']
export const LazyPaymentDialog: typeof import("../components/PaymentDialog.vue")['default']
export const LazySidebarMenu: typeof import("../components/Sidebar/Menu.vue")['default']
export const LazySidebar: typeof import("../components/Sidebar/index.vue")['default']
export const LazyLayoutFullLogo: typeof import("../components/layout/full/logo/Logo.vue")['default']
export const LazyLayoutFullLogoDark: typeof import("../components/layout/full/logo/LogoDark.vue")['default']
export const LazyLayoutFullVerticalHeaderNotificationDD: typeof import("../components/layout/full/vertical-header/NotificationDD.vue")['default']
export const LazyLayoutFullVerticalHeaderProfileDD: typeof import("../components/layout/full/vertical-header/ProfileDD.vue")['default']
export const LazyLayoutFullVerticalSidebarExtraBox: typeof import("../components/layout/full/vertical-sidebar/ExtraBox/index.vue")['default']
export const LazyLayoutFullVerticalSidebarNavGroup: typeof import("../components/layout/full/vertical-sidebar/NavGroup/index.vue")['default']
export const LazyLayoutFullVerticalSidebarNavItem: typeof import("../components/layout/full/vertical-sidebar/NavItem/index.vue")['default']
export const LazyLayoutFullVerticalSidebarItem: typeof import("../components/layout/full/vertical-sidebar/sidebarItem")['default']
export const LazyPaymentsDataTable: typeof import("../components/payments/DataTable.vue")['default']
export const LazyPaymentsDataTableDropDown: typeof import("../components/payments/DataTableDropDown.vue")['default']
export const LazyStudentsDataTable: typeof import("../components/students/DataTable.vue")['default']
export const LazyUAccordion: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Accordion.vue")['default']
export const LazyUAlert: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Alert.vue")['default']
export const LazyUAvatar: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Avatar.vue")['default']
export const LazyUAvatarGroup: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/AvatarGroup")['default']
export const LazyUBadge: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Badge.vue")['default']
export const LazyUButton: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Button.vue")['default']
export const LazyUButtonGroup: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/ButtonGroup")['default']
export const LazyUCarousel: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Carousel.vue")['default']
export const LazyUChip: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Chip.vue")['default']
export const LazyUDropdown: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Dropdown.vue")['default']
export const LazyUIcon: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Icon.vue")['default']
export const LazyUKbd: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Kbd.vue")['default']
export const LazyULink: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Link.vue")['default']
export const LazyUMeter: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Meter.vue")['default']
export const LazyUMeterGroup: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/MeterGroup")['default']
export const LazyUProgress: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Progress.vue")['default']
export const LazyUCheckbox: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Checkbox.vue")['default']
export const LazyUForm: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Form.vue")['default']
export const LazyUFormGroup: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/FormGroup.vue")['default']
export const LazyUInput: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Input.vue")['default']
export const LazyUInputMenu: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/InputMenu.vue")['default']
export const LazyURadio: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Radio.vue")['default']
export const LazyURadioGroup: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/RadioGroup.vue")['default']
export const LazyURange: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Range.vue")['default']
export const LazyUSelect: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Select.vue")['default']
export const LazyUSelectMenu: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/SelectMenu.vue")['default']
export const LazyUTextarea: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Textarea.vue")['default']
export const LazyUToggle: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Toggle.vue")['default']
export const LazyUTable: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/data/Table.vue")['default']
export const LazyUCard: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Card.vue")['default']
export const LazyUContainer: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Container.vue")['default']
export const LazyUDivider: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Divider.vue")['default']
export const LazyUSkeleton: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Skeleton.vue")['default']
export const LazyUBreadcrumb: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/Breadcrumb.vue")['default']
export const LazyUCommandPalette: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/CommandPalette.vue")['default']
export const LazyUCommandPaletteGroup: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/CommandPaletteGroup.vue")['default']
export const LazyUHorizontalNavigation: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/HorizontalNavigation.vue")['default']
export const LazyUPagination: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/Pagination.vue")['default']
export const LazyUTabs: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/Tabs.vue")['default']
export const LazyUVerticalNavigation: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/VerticalNavigation.vue")['default']
export const LazyUContextMenu: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/ContextMenu.vue")['default']
export const LazyUModal: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Modal.vue")['default']
export const LazyUModals: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Modals.client.vue")['default']
export const LazyUNotification: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Notification.vue")['default']
export const LazyUNotifications: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Notifications.vue")['default']
export const LazyUPopover: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Popover.vue")['default']
export const LazyUSlideover: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Slideover.vue")['default']
export const LazyUSlideovers: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Slideovers.client.vue")['default']
export const LazyUTooltip: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Tooltip.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyIcon: typeof import("../node_modules/@nuxt/icon/dist/runtime/components/index")['default']
export const LazyColorScheme: typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
export const LazySlide: typeof import("../node_modules/vue3-carousel/dist/carousel.es")['Slide']
export const LazyPagination: typeof import("../node_modules/vue3-carousel/dist/carousel.es")['Pagination']
export const LazyAccordion: typeof import("../components/ui/accordion/index")['Accordion']
export const LazyAccordionContent: typeof import("../components/ui/accordion/index")['AccordionContent']
export const LazyAccordionItem: typeof import("../components/ui/accordion/index")['AccordionItem']
export const LazyAccordionTrigger: typeof import("../components/ui/accordion/index")['AccordionTrigger']
export const LazyAlertDialog: typeof import("../components/ui/alert-dialog/index")['AlertDialog']
export const LazyAlertDialogTrigger: typeof import("../components/ui/alert-dialog/index")['AlertDialogTrigger']
export const LazyAlertDialogContent: typeof import("../components/ui/alert-dialog/index")['AlertDialogContent']
export const LazyAlertDialogHeader: typeof import("../components/ui/alert-dialog/index")['AlertDialogHeader']
export const LazyAlertDialogTitle: typeof import("../components/ui/alert-dialog/index")['AlertDialogTitle']
export const LazyAlertDialogDescription: typeof import("../components/ui/alert-dialog/index")['AlertDialogDescription']
export const LazyAlertDialogFooter: typeof import("../components/ui/alert-dialog/index")['AlertDialogFooter']
export const LazyAlertDialogAction: typeof import("../components/ui/alert-dialog/index")['AlertDialogAction']
export const LazyAlertDialogCancel: typeof import("../components/ui/alert-dialog/index")['AlertDialogCancel']
export const LazyBadge: typeof import("../components/ui/badge/index")['Badge']
export const LazyCalendar: typeof import("../components/ui/calendar/index")['Calendar']
export const LazyCalendarCell: typeof import("../components/ui/calendar/index")['CalendarCell']
export const LazyCalendarCellTrigger: typeof import("../components/ui/calendar/index")['CalendarCellTrigger']
export const LazyCalendarGrid: typeof import("../components/ui/calendar/index")['CalendarGrid']
export const LazyCalendarGridBody: typeof import("../components/ui/calendar/index")['CalendarGridBody']
export const LazyCalendarGridHead: typeof import("../components/ui/calendar/index")['CalendarGridHead']
export const LazyCalendarGridRow: typeof import("../components/ui/calendar/index")['CalendarGridRow']
export const LazyCalendarHeadCell: typeof import("../components/ui/calendar/index")['CalendarHeadCell']
export const LazyCalendarHeader: typeof import("../components/ui/calendar/index")['CalendarHeader']
export const LazyCalendarHeading: typeof import("../components/ui/calendar/index")['CalendarHeading']
export const LazyCalendarNextButton: typeof import("../components/ui/calendar/index")['CalendarNextButton']
export const LazyCalendarPrevButton: typeof import("../components/ui/calendar/index")['CalendarPrevButton']
export const LazyCardHeader: typeof import("../components/ui/card/index")['CardHeader']
export const LazyCardTitle: typeof import("../components/ui/card/index")['CardTitle']
export const LazyCardDescription: typeof import("../components/ui/card/index")['CardDescription']
export const LazyCardContent: typeof import("../components/ui/card/index")['CardContent']
export const LazyCardFooter: typeof import("../components/ui/card/index")['CardFooter']
export const LazyCarouselContent: typeof import("../components/ui/carousel/index")['CarouselContent']
export const LazyCarouselItem: typeof import("../components/ui/carousel/index")['CarouselItem']
export const LazyCarouselPrevious: typeof import("../components/ui/carousel/index")['CarouselPrevious']
export const LazyCarouselNext: typeof import("../components/ui/carousel/index")['CarouselNext']
export const LazyCarouselApi: typeof import("../components/ui/carousel/index")['CarouselApi']
export const LazyCheckbox: typeof import("../components/ui/checkbox/index")['Checkbox']
export const LazyDialog: typeof import("../components/ui/dialog/index")['Dialog']
export const LazyDialogClose: typeof import("../components/ui/dialog/index")['DialogClose']
export const LazyDialogTrigger: typeof import("../components/ui/dialog/index")['DialogTrigger']
export const LazyDialogHeader: typeof import("../components/ui/dialog/index")['DialogHeader']
export const LazyDialogTitle: typeof import("../components/ui/dialog/index")['DialogTitle']
export const LazyDialogDescription: typeof import("../components/ui/dialog/index")['DialogDescription']
export const LazyDialogContent: typeof import("../components/ui/dialog/index")['DialogContent']
export const LazyDialogScrollContent: typeof import("../components/ui/dialog/index")['DialogScrollContent']
export const LazyDialogFooter: typeof import("../components/ui/dialog/index")['DialogFooter']
export const LazyDropdownMenuPortal: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuPortal']
export const LazyDropdownMenu: typeof import("../components/ui/dropdown-menu/index")['DropdownMenu']
export const LazyDropdownMenuTrigger: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuTrigger']
export const LazyDropdownMenuContent: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuContent']
export const LazyDropdownMenuGroup: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuGroup']
export const LazyDropdownMenuRadioGroup: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioGroup']
export const LazyDropdownMenuItem: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuItem']
export const LazyDropdownMenuCheckboxItem: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuCheckboxItem']
export const LazyDropdownMenuRadioItem: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioItem']
export const LazyDropdownMenuShortcut: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuShortcut']
export const LazyDropdownMenuSeparator: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSeparator']
export const LazyDropdownMenuLabel: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuLabel']
export const LazyDropdownMenuSub: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSub']
export const LazyDropdownMenuSubTrigger: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubTrigger']
export const LazyDropdownMenuSubContent: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubContent']
export const LazyForm: typeof import("../components/ui/form/index")['Form']
export const LazyFormField: typeof import("../components/ui/form/index")['FormField']
export const LazyFormItem: typeof import("../components/ui/form/index")['FormItem']
export const LazyFormLabel: typeof import("../components/ui/form/index")['FormLabel']
export const LazyFormControl: typeof import("../components/ui/form/index")['FormControl']
export const LazyFormMessage: typeof import("../components/ui/form/index")['FormMessage']
export const LazyFormDescription: typeof import("../components/ui/form/index")['FormDescription']
export const LazyFORMITEMINJECTIONKEY: typeof import("../components/ui/form/index")['FORM_ITEM_INJECTION_KEY']
export const LazyPopover: typeof import("../components/ui/popover/index")['Popover']
export const LazyPopoverTrigger: typeof import("../components/ui/popover/index")['PopoverTrigger']
export const LazyPopoverContent: typeof import("../components/ui/popover/index")['PopoverContent']
export const LazyRangeCalendar: typeof import("../components/ui/range-calendar/index")['RangeCalendar']
export const LazyRangeCalendarCell: typeof import("../components/ui/range-calendar/index")['RangeCalendarCell']
export const LazyRangeCalendarCellTrigger: typeof import("../components/ui/range-calendar/index")['RangeCalendarCellTrigger']
export const LazyRangeCalendarGrid: typeof import("../components/ui/range-calendar/index")['RangeCalendarGrid']
export const LazyRangeCalendarGridBody: typeof import("../components/ui/range-calendar/index")['RangeCalendarGridBody']
export const LazyRangeCalendarGridHead: typeof import("../components/ui/range-calendar/index")['RangeCalendarGridHead']
export const LazyRangeCalendarGridRow: typeof import("../components/ui/range-calendar/index")['RangeCalendarGridRow']
export const LazyRangeCalendarHeadCell: typeof import("../components/ui/range-calendar/index")['RangeCalendarHeadCell']
export const LazyRangeCalendarHeader: typeof import("../components/ui/range-calendar/index")['RangeCalendarHeader']
export const LazyRangeCalendarHeading: typeof import("../components/ui/range-calendar/index")['RangeCalendarHeading']
export const LazyRangeCalendarNextButton: typeof import("../components/ui/range-calendar/index")['RangeCalendarNextButton']
export const LazyRangeCalendarPrevButton: typeof import("../components/ui/range-calendar/index")['RangeCalendarPrevButton']
export const LazySeparator: typeof import("../components/ui/separator/index")['Separator']
export const LazySheet: typeof import("../components/ui/sheet/index")['Sheet']
export const LazySheetTrigger: typeof import("../components/ui/sheet/index")['SheetTrigger']
export const LazySheetClose: typeof import("../components/ui/sheet/index")['SheetClose']
export const LazySheetContent: typeof import("../components/ui/sheet/index")['SheetContent']
export const LazySheetHeader: typeof import("../components/ui/sheet/index")['SheetHeader']
export const LazySheetTitle: typeof import("../components/ui/sheet/index")['SheetTitle']
export const LazySheetDescription: typeof import("../components/ui/sheet/index")['SheetDescription']
export const LazySheetFooter: typeof import("../components/ui/sheet/index")['SheetFooter']
export const LazyTable: typeof import("../components/ui/table/index")['Table']
export const LazyTableBody: typeof import("../components/ui/table/index")['TableBody']
export const LazyTableCell: typeof import("../components/ui/table/index")['TableCell']
export const LazyTableHead: typeof import("../components/ui/table/index")['TableHead']
export const LazyTableHeader: typeof import("../components/ui/table/index")['TableHeader']
export const LazyTableFooter: typeof import("../components/ui/table/index")['TableFooter']
export const LazyTableRow: typeof import("../components/ui/table/index")['TableRow']
export const LazyTableCaption: typeof import("../components/ui/table/index")['TableCaption']
export const LazyTableEmpty: typeof import("../components/ui/table/index")['TableEmpty']
export const LazyTagsInput: typeof import("../components/ui/tags-input/index")['TagsInput']
export const LazyTagsInputInput: typeof import("../components/ui/tags-input/index")['TagsInputInput']
export const LazyTagsInputItem: typeof import("../components/ui/tags-input/index")['TagsInputItem']
export const LazyTagsInputItemDelete: typeof import("../components/ui/tags-input/index")['TagsInputItemDelete']
export const LazyTagsInputItemText: typeof import("../components/ui/tags-input/index")['TagsInputItemText']
export const LazyTextarea: typeof import("../components/ui/textarea/index")['Textarea']
export const LazyToaster: typeof import("../components/ui/toast/index")['Toaster']
export const LazyToast: typeof import("../components/ui/toast/index")['Toast']
export const LazyToastViewport: typeof import("../components/ui/toast/index")['ToastViewport']
export const LazyToastAction: typeof import("../components/ui/toast/index")['ToastAction']
export const LazyToastClose: typeof import("../components/ui/toast/index")['ToastClose']
export const LazyToastTitle: typeof import("../components/ui/toast/index")['ToastTitle']
export const LazyToastDescription: typeof import("../components/ui/toast/index")['ToastDescription']
export const LazyToastProvider: typeof import("../components/ui/toast/index")['ToastProvider']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyUModals: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyUSlideovers: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
